# Generated by Django 4.2.11 on 2024-04-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_keywords',
            field=models.JSONField(default=[], verbose_name='Ключевые слова'),
        ),
    ]
