# Generated by Django 4.2.11 on 2024-04-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_article_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_keywords',
        ),
    ]
