# Generated by Django 5.0.6 on 2024-06-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_article_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_annotation',
            field=models.TextField(default=None, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_issn',
            field=models.TextField(default=None, verbose_name='ISSN'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_science',
            field=models.TextField(default=None, verbose_name='Научное направление'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_keywords',
            field=models.JSONField(default='{"0": []}', verbose_name='Ключевые слова'),
        ),
    ]
